### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by ArquintL** [viperproject/vs-verification-toolbox#6]
Having `"vs-verification-toolbox": "github:viperproject/vs-verification-toolbox#master"` as a devDependency works on my local machine (macOS; node v14.10.1; npm 6.14.8). This means, that vs-verification-toolbox is compiled as part of `npm install` resp. `npm ci` (i.e. the prepare step is triggered).

However, I observed a (consistently) different behavior in my docker container (`gobraverifier/gobra-ide-base:v1`) running Ubuntu 20.04 (node v10.19.0; npm 6.14.4). This repo's content is downloaded but compilation is not triggered. In particular, the out folder is missing. As a quick fix, I perform now `cd node_modules/vs-verification-toolbox; npm install; npm run compile;` to manually compile this library after downloading it.
I first thought it might be related to the missing `files` property in package.json, but adding the out folder seemed to make things worse.

**Comment by fpoli** [comment]
The problem seems to be this one: https://stackoverflow.com/questions/51078974/how-to-have-npm-install-a-typescript-dependency-from-a-github-url

Some solutions:
a) Make the user automatically compile the toolbox [using this suggestion](https://stackoverflow.com/a/55075721/2491528). This requires all users to have typescript installed.
b) Always compile and push the generated `.js` files to Github.
c) Manually compile the dependency, as you are doing.

If it works, I would prefer solution (a).

**Comment by ArquintL** [comment]
I think solution a) is already implemented in the repo (there's a `prepare` step compiling vs-verification-toolbox. The strange thing however is that it works on my local machine but not in the docker image

**Comment by fpoli** [comment]
Could you try if the `prepack` works, in place of the `prepare`?

**Comment by fpoli** [comment]
Also, could you check if npm's `ignore-scripts` configuration flag is set to `true` in the docker image?

**Comment by ArquintL** [comment]
I've now created a non-root user for my docker image and let it run the commands. The same issue occurs when using `npm ci` but `npm install` will correctly compile vs-verification-toolbox as specified in `prepare`. This is possibly related to this issue: https://github.com/npm/cli/issues/1287

I'll try the suggestions later this week and correspondingly update this issue

**Comment by juliand665** [comment]
I'd also be curious if `"vs-verification-toolbox": "https://github.com/viperproject/vs-verification-toolbox.git"` works; that's the form I've been using in [Prusti Assistant](https://github.com/juliand665/prusti-assistant/blob/master/package.json) since none of the others seemed to work.

**Comment by ArquintL** [comment]
## Docker using non-root user
`"vs-verification-toolbox": "https://github.com/viperproject/vs-verification-toolbox.git"` fixes the issue for `npm install` as well as `npm ci`.
another try with `"vs-verification-toolbox": "github:viperproject/vs-verification-toolbox#master"` seemed to work in both cases as well.

## Docker using root user
`prepare` does not seem to be executed neither with `npm install` nor `npm ci`, neither with `"vs-verification-toolbox": "github:viperproject/vs-verification-toolbox#master"` nor `"vs-verification-toolbox": "https://github.com/viperproject/vs-verification-toolbox.git"`

## Conclusions
It seems to only depend on the root / non-root docker user. @juliand665 I did not observe any problems using different URL schemes, even `"vs-verification-toolbox": "git://github.com/viperproject/vs-verification-toolbox.git"` works on my end.

I've found out that vscode needs root access to install an extension for testing. Therefore, I run `npm test` as root but `npm ci` as a non-root user. In addition, I'm using now `"vs-verification-toolbox": "git://github.com/viperproject/vs-verification-toolbox"` (as this URL schema is one of the specified ones in the [documentation](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies))
